#!/bin/bash
#
# Check code style before commit.

# Need to check whether the installation package
install_pkgs=(jshint jscs coffeelint scss-lint)

for pkg_name in ${install_pkgs[@]}
do
    which ${pkg_name} &> /dev/null
    if [ $? -ne 0 ]; then
        echo ""
        echo -e "\033[1;41mERROR\033[0m: ${pkg_name} not found"
        if [ $pkg_name == 'scss-lint' ]; then
            echo "INSTALL WITH: sudo gem install scss-lint"
        else
            echo "INSTALL WITH: sudo npm install -g ${pkg_name}"
        fi
        exit 1
    fi
done

# Configuration need to check the file
check="git diff --cached --name-only --diff-filter=ACMR --"
js_files=$(${check} src/js/*.js)
coffee_files=$(${check} src/coffee/*.coffee)
scss_files=$(${check} src/scss/*.scss)

# Kit json configuration file
root=$(git rev-parse --show-toplevel)
jscs_conf="${root}/jscs.json"
jshint_conf="${root}/jshint.json"
scsslint_conf="${root}/scsslint.json"
coffeelint_conf="${root}/coffeelint.json"

# Check code default prompt information
function echoPrompt() {
    if $1; then
        echo -e "\033[1;32mOk! >>\033[0m check through the $2 code style."
    else
        echo -e "\n\033[1;41mCOMMIT FAILED\033[0m:\n\
Some $2 files are invalid. Please fix errors and try committing again."
        exit 1
    fi
}

# To determine whether these modified files is added
function isAdded() {
    for file in $1; do
        grep ^${file}$ change_file_log
        if [ $? -ne 0 ]; then
            echo -e "\033[1;41mERROR\033[0m:\
Please use \033[1;34m'git add'\033[0m command to increases the modified files and try committing again."
            exit 1
        fi
    done
}

# JS code check
# Jscs and JSHint
js_pass=true

if [ "$js_files" != "" ]; then
    echo -e "\033[1;34mjs code check\033[0m:\n$js_files"
    for file in ${js_files}; do
        jscs ${file} -c ${jscs_conf}
        if [[ $? -ne 0 ]]; then
            js_pass=false
        fi
    done
    for file in ${js_files}; do
        jshint ${file} -c ${jshint_conf}
        if [[ $? -ne 0 ]]; then
            js_pass=false
        fi
    done
    echoPrompt $js_pass "js"
fi

# Coffee code check
# CoffeeLint
coffee_pass=true

if [ "$coffee_files" != "" ]; then
    isAdded $coffee_files
    echo $coffee_files > change_file_log
    echo -e "\n\033[1;34mcoffee code check\033[0m:\n$coffee_files"
    for file in ${coffee_files}; do
        coffeelint -f ${coffeelint_conf} ${file}
        if [[ $? -ne 0 ]]; then
            coffee_pass=false
        fi
    done
    echoPrompt $coffee_pass "coffee"
fi

# Scss code check
# ScssLint
scss_pass=true

if [ "$scss_files" != "" ]; then
    echo -e "\n\033[1;34mscss code check\033[0m:\n$scss_files"
    for file in ${scss_files}; do
        scss-lint -c ${scsslint_conf} ${file}
        if [[ $? -ne 0 ]]; then
            scss_pass=false
        fi
    done
    echoPrompt $scss_pass "scss"
fi

if [ $js_pass -a $coffee_pass -a $scss_pass ]; then
    exit 0
fi
