#!/bin/bash
#
# Check code style before commit.

# Need to check whether the installation package
install_pkgs=(jshint jscs coffeelint scss-lint)

for pkg_name in ${install_pkgs[@]}
do
    which ${pkg_name} &> /dev/null
    if [ $? -ne 0 ]; then
        echo ""
        echo -e "\033[1;41mERROR\033[0m: ${pkg_name} not found"
        if [ $pkg_name == 'scss-lint' ]; then
            echo "INSTALL WITH: sudo gem install scss-lint"
        else
            echo "INSTALL WITH: sudo npm install -g ${pkg_name}"
        fi
        exit 1
    fi
done

# Configuration need to check the file
straged="git diff --cached --name-only --diff-filter=ACMR --"
unstraged="git diff --name-only --diff-filter=ACMR --"
js_files="*.js"
coffee_files="*.coffee"
scss_files="*.scss"

# Kit json configuration file
root=$(git rev-parse --show-toplevel)
jscs_conf="${root}/jscs.json"
jshint_conf="${root}/jshint.json"
coffeelint_conf="${root}/coffeelint.json"
scsslint_conf="${root}/scsslint.json"

# Check code default prompt information
function echoPrompt() {
    if $1; then
        echo -e "\033[1;32mOk! >>\033[0m check through the $2 code style."
    else
        echo -e "\n\033[1;41mCOMMIT FAILED\033[0m:\n\
Some $2 files are invalid. Please fix errors and try committing again."
        exit 1
    fi
}

# To determine whether these modified files is added
function isAdded() {
    if [ "$1" != "" ]; then
        for file in $1; do
            if [[ $2 =~ ${file} ]]; then
                echo -e "Changes not staged for commit:\n\
\t(use 'git add <file>...' to update what will be committed)\n\
\033[31m$1\033[0m"
                exit 1
            fi
        done
    fi
}

##### JS code check #####
# Jscs and JSHint
js_pass=true
straged_js_files=$(${straged} ${js_files})
unstraged_js_files=$(${unstraged} ${js_files})

if [ "$straged_js_files" != "" ]; then
    isAdded "$unstraged_js_files" "$straged_js_files"
    echo -e "\033[1;34mjs code check\033[0m:\n$straged_js_files"
    for file in ${straged_js_files}; do
        jscs ${file} -c ${jscs_conf}
        if [[ $? -ne 0 ]]; then
            js_pass=false
        fi
    done
    for file in ${straged_js_files}; do
        jshint ${file} -c ${jshint_conf}
        if [[ $? -ne 0 ]]; then
            js_pass=false
        fi
    done
    echoPrompt $js_pass "js"
fi

##### Coffee code check #####
# CoffeeLint
coffee_pass=true
straged_coffee_files=$(${straged} ${coffee_files})
unstraged_coffee_files=$(${unstraged} ${coffee_files})

if [ "$straged_coffee_files" != "" ]; then
    isAdded "$unstraged_coffee_files" "$straged_coffee_files"
    echo -e "\n\033[1;34mcoffee code check\033[0m:\n$straged_coffee_files"
    for file in ${straged_coffee_files}; do
        coffeelint -f ${coffeelint_conf} ${file}
        if [[ $? -ne 0 ]]; then
            coffee_pass=false
        fi
    done
    echoPrompt $coffee_pass "coffee"
fi

##### Scss code check #####
# ScssLint
scss_pass=true
straged_scss_files=$(${straged} ${scss_files})
unstraged_scss_files=$(${unstraged} ${scss_files})

if [ "$straged_scss_files" != "" ]; then
    isAdded "$unstraged_scss_files" "$straged_scss_files"
    echo -e "\n\033[1;34mscss code check\033[0m:\n$straged_scss_files"
    for file in ${straged_scss_files}; do
        scss-lint -c ${scsslint_conf} ${file}
        if [[ $? -ne 0 ]]; then
            scss_pass=false
        fi
    done
    echoPrompt $scss_pass "scss"
fi

if [ $js_pass -a $coffee_pass -a $scss_pass ]; then
    exit 0
fi
